#4410 Fix for Internal Error: SQL Error: SQLSTATE[HY000]: General err…
kanboard/kanboard pull request #4978
Opened 2022-03-15 13:42 UTC by emojized

…or: 1 no such table: main.task_has_subtasks in SQLite

Do you follow the guidelines?

- [x] I have tested my changes
- [x] There is no breaking change
- [x] There is no regression
- [x] I follow existing [coding style](https://docs.kanboard.org/en/latest/developer_guide/coding_standards.html)

2022-03-16 16:20 UTC, jonatasartur commented
Thank you.
This solution solved my problem of `Internal Error: SQL Error: SQLSTATE[HY000]: General error: 1 no such table: main.task_has_subtasks` in subtasks

2022-03-17 08:45 UTC, BerkhanBerkdemir requested changes
Other than some make up in the code, this is a valid way to fix the SQLite issue on Kanboard. Thanks for the patch!

2022-03-17 08:45 UTC, BerkhanBerkdemir commented on app/Schema/Sqlite.php
> +    $pdo->exec("
Please either use " or ' in your code.

2022-03-17 08:45 UTC, BerkhanBerkdemir commented on app/Schema/Sqlite.php
> +    $pdo->exec('CREATE INDEX subtasks_task_idx ON subtasks(task_id)');
Code indentation needs to be followed in here like other lines.

2022-03-18 01:10 UTC, merged